
import json
import uuid
import asyncio
import shutil
import os

from fastapi import APIRouter, Depends, HTTPException, UploadFile, File
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from typing import Optional
from langchain_core.messages import HumanMessage

from app.agent.graph import booking_agent
from app.auth.authentication import get_current_User
from app.db.models import User
from app.services.stt_service import STTService
from app.services.tts_service import TTSService
from app.utils.helper import is_sentence_end, clean_for_tts

router = APIRouter(tags=["Agent"], prefix="/agent")

stt = STTService()
tts = TTSService()

UPLOAD_DIR = "temp_uploads"
os.makedirs(UPLOAD_DIR, exist_ok=True)



# Schemas / later will shift to seperate file


class ChatRequest(BaseModel):
    message: str
    session_id: Optional[str] = None  # None = new session


class SessionResponse(BaseModel):
    session_id: str



# Helper: Build LangGraph config for a session + user


def get_agent_config(session_id: str, user: User) -> dict:
    return {
        "configurable": {
            "thread_id": session_id,
            "user_id": str(user.id),
            "user_name": user.full_name,
        }
    }



# 1. Start a new session


@router.post("/session", response_model=SessionResponse)
async def create_session(current_user: User = Depends(get_current_User)):
    """Creates a new conversation session and returns its ID."""
    return {"session_id": str(uuid.uuid4())}



# 2. Text Chat with streaming SSE response


@router.post("/chat")
async def chat(
    request: ChatRequest,
    current_user: User = Depends(get_current_User),
):
    """
    Send a text message to the booking agent.
    Returns a streaming Server-Sent Events (SSE) response.
    If no session_id is provided, a new session is created.
    """
    session_id = request.session_id or str(uuid.uuid4())
    config = get_agent_config(session_id, current_user)
    config["configurable"]["mode"] = "text"

    input_state = {
        "messages": [HumanMessage(content=request.message)],
        "user_id": str(current_user.id),
        "user_name": current_user.full_name
    }

    async def event_stream():
        try:
            # Stream events from the agent graph
            async for event in booking_agent.astream_events(
                input_state,
                config=config,
                version="v2"
            ):
                kind = event.get("event")

                # Stream each token as it's generated by the LLM
                if kind == "on_chat_model_stream":
                    chunk = event["data"].get("chunk")
                    if chunk and hasattr(chunk, "content") and chunk.content:
                        yield f"data: {json.dumps({'type': 'token', 'text': chunk.content, 'session_id': session_id})}\n\n"

                # Notify client when a tool is being called
                elif kind == "on_tool_start":
                    tool_name = event.get("name", "")
                    yield f"data: {json.dumps({'type': 'tool_call', 'tool': tool_name})}\n\n"

                # Stream tool results for transparency
                elif kind == "on_tool_end":
                    tool_name = event.get("name", "")
                    yield f"data: {json.dumps({'type': 'tool_result', 'tool': tool_name})}\n\n"

            yield f"data: {json.dumps({'type': 'done', 'session_id': session_id})}\n\n"

        except Exception as e:
            yield f"data: {json.dumps({'type': 'error', 'message': str(e)})}\n\n"

    return StreamingResponse(
        event_stream(),
        media_type="text/event-stream",
        headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"},
    )



# 3. Voice Chat: STT → Agent → TTS (streaming SSE)


@router.post("/voice")
async def voice_chat(
    file: UploadFile = File(...),
    session_id: Optional[str] = None,
    current_user: User = Depends(get_current_User),
):
    """
    Full voice pipeline:
    1. Transcribe audio (STT)
    2. Run through the booking agent
    3. Convert response to audio (TTS) sentence by sentence
    Returns a streaming SSE response with both text tokens and audio chunks.
    """
    active_session_id = session_id or str(uuid.uuid4())
    file_id = str(uuid.uuid4())
    input_path = os.path.join(UPLOAD_DIR, f"{file_id}.wav")

    with open(input_path, "wb") as f:
        shutil.copyfileobj(file.file, f)

    async def event_stream():
        loop = asyncio.get_event_loop()
        try:
            # ── 1. STT ─────────────────────────────────────────────────────
            text_input = await loop.run_in_executor(None, stt.transcribe, input_path)
            if not text_input:
                yield f"data: {json.dumps({'type': 'error', 'message': 'Could not understand audio'})}\n\n"
                return

            yield f"data: {json.dumps({'type': 'user_text', 'text': text_input, 'session_id': active_session_id})}\n\n"

            # ── 2. Agent ────────────────────────────────────────────────────
            config = get_agent_config(active_session_id, current_user)
            config["configurable"]["mode"] = "voice"
            input_state = {
                "messages": [HumanMessage(content=text_input)],
                "user_id": str(current_user.id),
                "user_name": current_user.full_name
            }

            sentence_buffer = ""

            async for event in booking_agent.astream_events(
                input_state,
                config=config,
                version="v2"
            ):
                kind = event.get("event")

                if kind == "on_chat_model_stream":
                    chunk = event["data"].get("chunk")
                    if chunk and hasattr(chunk, "content") and chunk.content:
                        token = chunk.content
                        yield f"data: {json.dumps({'type': 'ai_token', 'token': token})}\n\n"
                        sentence_buffer += token

                        # ── 3. TTS per sentence ─────────────────────────────
                        if is_sentence_end(sentence_buffer):
                            sentence = sentence_buffer.strip()
                            sentence_buffer = ""
                            voice_text = clean_for_tts(sentence)
                            audio_b64 = await loop.run_in_executor(
                                None, tts.generate_audio_base64, voice_text
                            )
                            if audio_b64:
                                yield f"data: {json.dumps({'type': 'audio_chunk', 'audio': audio_b64, 'text': sentence})}\n\n"

                elif kind == "on_tool_start":
                    yield f"data: {json.dumps({'type': 'tool_call', 'tool': event.get('name', '')})}\n\n"

            # Flush remaining buffer
            if sentence_buffer.strip():
                final = sentence_buffer.strip()
                audio_b64 = await loop.run_in_executor(
                    None, tts.generate_audio_base64, clean_for_tts(final)
                )
                if audio_b64:
                    yield f"data: {json.dumps({'type': 'audio_chunk', 'audio': audio_b64, 'text': final})}\n\n"

            yield f"data: {json.dumps({'type': 'done', 'session_id': active_session_id})}\n\n"

        except Exception as e:
            yield f"data: {json.dumps({'type': 'error', 'message': str(e)})}\n\n"
        finally:
            if os.path.exists(input_path):
                os.remove(input_path)

    return StreamingResponse(
        event_stream(),
        media_type="text/event-stream",
        headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"},
    )
