"""Added Initial Schema

Revision ID: 4cc85a66c6b9
Revises: 
Create Date: 2026-04-30 10:01:38.325794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4cc85a66c6b9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('rating', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('rating >= 0 AND rating <= 5', name='check_hotel_rating'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_hotels_city', 'hotels', ['city'], unique=False)
    op.create_index('idx_hotels_country', 'hotels', ['country'], unique=False)
    op.create_table('token_blacklist',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('blacklisted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index('idx_token_blacklist_expires', 'token_blacklist', ['expires_at'], unique=False)
    op.create_index(op.f('ix_token_blacklist_token'), 'token_blacklist', ['token'], unique=False)
    op.create_index(op.f('ix_token_blacklist_user_id'), 'token_blacklist', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='userrole'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'BANNED', name='userstatus'), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('reset_password_otp', sa.String(length=10), nullable=True),
    sa.Column('reset_password_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_created_at', 'users', ['created_at'], unique=False)
    op.create_index('idx_users_email_active', 'users', ['email'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_users_role_status', 'users', ['role', 'status'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('conversation_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('session_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sessions_updated_at', 'conversation_sessions', ['updated_at'], unique=False)
    op.create_index('idx_sessions_user', 'conversation_sessions', ['user_id'], unique=False)
    op.create_table('room_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('max_guests', sa.Integer(), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('amenities', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('base_price >= 0', name='check_base_price'),
    sa.CheckConstraint('max_guests > 0', name='check_max_guests'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_room_types_amenities', 'room_types', ['amenities'], unique=False, postgresql_using='gin')
    op.create_index('idx_room_types_hotel', 'room_types', ['hotel_id'], unique=False)
    op.create_index(op.f('ix_room_types_hotel_id'), 'room_types', ['hotel_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'TOOL', name='messagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['conversation_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_messages_created_at', 'messages', ['created_at'], unique=False)
    op.create_index('idx_messages_role', 'messages', ['session_id', 'role'], unique=False)
    op.create_index('idx_messages_session', 'messages', ['session_id'], unique=False)
    op.create_index(op.f('ix_messages_session_id'), 'messages', ['session_id'], unique=False)
    op.create_table('rooms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('room_type_id', sa.UUID(), nullable=False),
    sa.Column('room_number', sa.String(length=20), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'MAINTENANCE', name='roomstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('floor >= 0', name='check_floor'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rooms_active', 'rooms', ['hotel_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_rooms_hotel_status', 'rooms', ['hotel_id', 'status'], unique=False)
    op.create_index(op.f('ix_rooms_hotel_id'), 'rooms', ['hotel_id'], unique=False)
    op.create_index(op.f('ix_rooms_room_type_id'), 'rooms', ['room_type_id'], unique=False)
    op.create_table('reservation_locks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_locks_expiry', 'reservation_locks', ['expires_at'], unique=False)
    op.create_index('idx_locks_room', 'reservation_locks', ['room_id', 'expires_at'], unique=False)
    op.create_index('idx_locks_session', 'reservation_locks', ['session_id'], unique=False)
    op.create_index(op.f('ix_reservation_locks_room_id'), 'reservation_locks', ['room_id'], unique=False)
    op.create_table('reservations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('checkin_date', sa.Date(), nullable=False),
    sa.Column('checkout_date', sa.Date(), nullable=False),
    sa.Column('guest_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED', 'NO_SHOW', name='reservationstatus'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('confirmation_code', sa.String(length=50), nullable=True),
    sa.Column('special_requests', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('checkout_date > checkin_date', name='check_checkout_after_checkin'),
    sa.CheckConstraint('guest_count > 0', name='check_guest_count'),
    sa.CheckConstraint('total_amount IS NULL OR total_amount >= 0', name='check_total_amount'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reservations_dates', 'reservations', ['checkin_date', 'checkout_date'], unique=False)
    op.create_index('idx_reservations_hotel', 'reservations', ['hotel_id'], unique=False)
    op.create_index('idx_reservations_status', 'reservations', ['status'], unique=False)
    op.create_index('idx_reservations_user', 'reservations', ['user_id'], unique=False)
    op.create_index(op.f('ix_reservations_confirmation_code'), 'reservations', ['confirmation_code'], unique=True)
    op.create_index(op.f('ix_reservations_hotel_id'), 'reservations', ['hotel_id'], unique=False)
    op.create_index(op.f('ix_reservations_room_id'), 'reservations', ['room_id'], unique=False)
    op.create_index(op.f('ix_reservations_user_id'), 'reservations', ['user_id'], unique=False)
    op.create_table('room_inventory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('inventory_date', sa.Date(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('price_override', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('price_override IS NULL OR price_override >= 0', name='check_price_override'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inventory_available', 'room_inventory', ['room_id', 'inventory_date'], unique=False, postgresql_where=sa.text('is_available IS true'))
    op.create_index('idx_inventory_date', 'room_inventory', ['inventory_date'], unique=False)
    op.create_index('idx_inventory_room_date', 'room_inventory', ['room_id', 'inventory_date'], unique=False)
    op.create_index(op.f('ix_room_inventory_room_id'), 'room_inventory', ['room_id'], unique=False)
    op.create_index('uq_room_inventory_date', 'room_inventory', ['room_id', 'inventory_date'], unique=True)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reservation_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('transaction_ref', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('INITIATED', 'PAID', 'FAILED', 'REFUNDED', name='paymentstatus'), nullable=False),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='check_payment_amount'),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_ref')
    )
    op.create_index('idx_payments_reservation', 'payments', ['reservation_id'], unique=False)
    op.create_index('idx_payments_status', 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_reservation_id'), 'payments', ['reservation_id'], unique=False)
    op.create_table('reservation_guests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reservation_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservation_guests_reservation_id'), 'reservation_guests', ['reservation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reservation_guests_reservation_id'), table_name='reservation_guests')
    op.drop_table('reservation_guests')
    op.drop_index(op.f('ix_payments_reservation_id'), table_name='payments')
    op.drop_index('idx_payments_status', table_name='payments')
    op.drop_index('idx_payments_reservation', table_name='payments')
    op.drop_table('payments')
    op.drop_index('uq_room_inventory_date', table_name='room_inventory')
    op.drop_index(op.f('ix_room_inventory_room_id'), table_name='room_inventory')
    op.drop_index('idx_inventory_room_date', table_name='room_inventory')
    op.drop_index('idx_inventory_date', table_name='room_inventory')
    op.drop_index('idx_inventory_available', table_name='room_inventory', postgresql_where=sa.text('is_available IS true'))
    op.drop_table('room_inventory')
    op.drop_index(op.f('ix_reservations_user_id'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_room_id'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_hotel_id'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_confirmation_code'), table_name='reservations')
    op.drop_index('idx_reservations_user', table_name='reservations')
    op.drop_index('idx_reservations_status', table_name='reservations')
    op.drop_index('idx_reservations_hotel', table_name='reservations')
    op.drop_index('idx_reservations_dates', table_name='reservations')
    op.drop_table('reservations')
    op.drop_index(op.f('ix_reservation_locks_room_id'), table_name='reservation_locks')
    op.drop_index('idx_locks_session', table_name='reservation_locks')
    op.drop_index('idx_locks_room', table_name='reservation_locks')
    op.drop_index('idx_locks_expiry', table_name='reservation_locks')
    op.drop_table('reservation_locks')
    op.drop_index(op.f('ix_rooms_room_type_id'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_hotel_id'), table_name='rooms')
    op.drop_index('idx_rooms_hotel_status', table_name='rooms')
    op.drop_index('idx_rooms_active', table_name='rooms', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('rooms')
    op.drop_index(op.f('ix_messages_session_id'), table_name='messages')
    op.drop_index('idx_messages_session', table_name='messages')
    op.drop_index('idx_messages_role', table_name='messages')
    op.drop_index('idx_messages_created_at', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_room_types_hotel_id'), table_name='room_types')
    op.drop_index('idx_room_types_hotel', table_name='room_types')
    op.drop_index('idx_room_types_amenities', table_name='room_types', postgresql_using='gin')
    op.drop_table('room_types')
    op.drop_index('idx_sessions_user', table_name='conversation_sessions')
    op.drop_index('idx_sessions_updated_at', table_name='conversation_sessions')
    op.drop_table('conversation_sessions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_users_role_status', table_name='users')
    op.drop_index('idx_users_email_active', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_users_created_at', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_token_blacklist_user_id'), table_name='token_blacklist')
    op.drop_index(op.f('ix_token_blacklist_token'), table_name='token_blacklist')
    op.drop_index('idx_token_blacklist_expires', table_name='token_blacklist')
    op.drop_table('token_blacklist')
    op.drop_index('idx_hotels_country', table_name='hotels')
    op.drop_index('idx_hotels_city', table_name='hotels')
    op.drop_table('hotels')
    # ### end Alembic commands ###
