"""Add menu and order models

Revision ID: dd7342ca08d4
Revises: 4cc85a66c6b9
Create Date: 2026-05-21 10:47:33.281895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd7342ca08d4'
down_revision: Union[str, Sequence[str], None] = '4cc85a66c6b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_menus',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('menu_date', sa.Date(), nullable=False),
    sa.Column('menu_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_daily_menu_date', 'daily_menus', ['menu_date'], unique=False)
    op.create_index(op.f('ix_daily_menus_hotel_id'), 'daily_menus', ['hotel_id'], unique=False)
    op.create_index('uq_daily_menu_date', 'daily_menus', ['hotel_id', 'menu_date'], unique=True)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reservation_id', sa.UUID(), nullable=False),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PREPARING', 'DELIVERED', 'CANCELLED', name='orderstatus'), nullable=False),
    sa.Column('special_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('total_amount >= 0', name='check_order_total'),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_orders_reservation', 'orders', ['reservation_id'], unique=False)
    op.create_index('idx_orders_status', 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_reservation_id'), 'orders', ['reservation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_reservation_id'), table_name='orders')
    op.drop_index('idx_orders_status', table_name='orders')
    op.drop_index('idx_orders_reservation', table_name='orders')
    op.drop_table('orders')
    op.drop_index('uq_daily_menu_date', table_name='daily_menus')
    op.drop_index(op.f('ix_daily_menus_hotel_id'), table_name='daily_menus')
    op.drop_index('idx_daily_menu_date', table_name='daily_menus')
    op.drop_table('daily_menus')
    # ### end Alembic commands ###
